### ISSUE TITLE
`getWpHostname()` Type error causes `npx depcheck to fail`

### ISSUE THREAD

**Issue by justlevine** [wpengine/faustjs#1410]
I am getting the following error when trying to run `npx depcheck` on my project.
```
Next.js webpack configuration detection failed with the following error TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at getWpHostname (/shared/httpd/axepress/htdocs/app/node_modules/@faustwp/core/dist/cjs/lib/getWpHostname.js:8:22)
    at Object.<anonymous> (/shared/httpd/axepress/htdocs/app/next.config.js:49:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  input: '',
  code: 'ERR_INVALID_URL'
} Support for this feature is new and experimental, please report issues at https://github.com/depcheck/depcheck/issues
```
It's pointing to the function's use of `new URL` [here](https://github.com/wpengine/faustjs/blob/854ecea5c6f5f94fd7cda49128693345d6d1f15a/packages/faustwp-core/src/lib/getWpHostname.ts#L6), but thats as far as my TS skills go.

###
Replication: 
```js
// next.config.js

const { withFaust, getWpHostname } = require( '@faustwp/core' ); // eslint-disable-line @typescript-eslint/no-var-requires

/**
 * @type {import('next').NextConfig}
 */
module.exports = withFaust( {
		typescript: {
			// !! WARN !!
			// Dangerously allow production builds to successfully complete even if
			// your project has type errors.
			// !! WARN !!
			ignoreBuildErrors: true,
		},
		swcMinify: true,
		trailingSlash: true,
		reactStrictMode: true,
		compress: true,
		productionBrowserSourceMaps: true,
		experimental: {
			runtime: 'nodejs',
		},
		pageExtensions: [ 'ts', 'tsx', 'js', 'jsx' ],
		images: {
			domains: [
				getWpHostname(),
				process.env.NEXT_PUBLIC_WORDPRESS_URL,
			],
			minimumCacheTTL: 31536000,
		},
		sassOptions: {
			includePaths: [ 'node_modules', './src' ],
		},
		async redirects() {
			return require( './redirects.json' );
		},
	},
);

**Comment by theodesp** [comment]
I had a quick look at this.

The `depcheck` tries to load the `webpack` config in this line:

https://github.com/depcheck/depcheck/blob/da616e724a5a33703cbaa17965e0ad90595198d2/src/special/webpack.js#L166

It tries to load the `next.config.js` config in your project folder.

Then the `getWpHostname()` is called however this does not load the env files from .env so it fails.

What you want to do is install depcheck globally

```
npm install -g depcheck 
```

Then export the `NEXT_PUBLIC_WORDPRESS_URL=http://mysite.local/` before you run depcheck.

```
export NEXT_PUBLIC_WORDPRESS_URL=http://mysite.local/

❯ npx depcheck
Missing dependencies
* breakpoints: ./styles/global.scss
* css-variables: ./styles/global.scss
* base: ./styles/global.scss
* utilities: ./styles/global.scss
* styles: ./components/NavigationMenu/NavigationMenu.module.scss
```

I'm moving this to a Q/A discussion threat since it's not an issue.
