### ISSUE TITLE
Render an Apollo Error's response body during unsuccessful responses

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#1732]
When receiving an unsuccessful response in Faust via Apollo, an `ApolloError` will be thrown. For example, during a Next.js prerendering error:

```
Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error
ApolloError: Response not successful: Received status code 500

at new ApolloError (/workspace/node_modules/@apollo/client/errors/errors.cjs:31:28)
at /workspace/node_modules/@apollo/client/core/core.cjs:1863:19
at both (/workspace/node_modules/@apollo/client/utilities/utilities.cjs:1072:53)
at /workspace/node_modules/@apollo/client/utilities/utilities.cjs:1065:72
at new Promise (<anonymous>)
at Object.then (/workspace/node_modules/@apollo/client/utilities/utilities.cjs:1065:24)
at Object.error (/workspace/node_modules/@apollo/client/utilities/utilities.cjs:1073:49)
at notifySubscription (/workspace/node_modules/zen-observable/lib/Observable.js:140:18)
at onNotify (/workspace/node_modules/zen-observable/lib/Observable.js:179:3)
at SubscriptionObserver.error (/workspace/node_modules/zen-observable/lib/Observable.js:240:7)
```

It would be helpful from a developer experience perspective to also show the response's body here, as they can determine further what the reason for the unsuccessful response was.

**Comment by TeresaGobble** [comment]
Hi @theodesp , confirming that this is the corresponding PR: https://github.com/wpengine/faustjs/pull/1832

**Comment by mindctrl** [comment]
@TeresaGobble that's it. I'll link the PR to the issue now.
