### ISSUE TITLE
Search bar on Faustjs.org is broken

### ISSUE THREAD

**Issue by miacias** [wpengine/faustjs#1873]
### Description

The search bar feature on the top right of the Faustjs.org documentation website has not been working for the last ~2 weeks as of April 10, 2024.

Below are screenshots and console errors related to this issue:

<img width="1680" alt="screenshot of Faustjs search bar and browser console" src="https://github.com/wpengine/faustjs/assets/113298622/24f91c9d-5179-47ec-b53c-fed93d9db2bf">

Token returns 401 status code: Unauthorized

<img width="1089" alt="screenshot of Network tab" src="https://github.com/wpengine/faustjs/assets/113298622/6af10fc4-91e8-4b9f-8f76-5ec28f84ef6f">

---

```
Failed to load resource: the server responded with a status of 401 ()
_app-d844a6410e282f58.js:141 
        
        
GET https://faustjs.org/api/faust/auth/token 401 (Unauthorized)
o9 @ _app-d844a6410e282f58.js:141
ae @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
uU @ framework-66d32731bdd20e83.js:9
oV @ framework-66d32731bdd20e83.js:9
oP @ framework-66d32731bdd20e83.js:9
r8 @ framework-66d32731bdd20e83.js:9
(anonymous) @ framework-66d32731bdd20e83.js:9
oU @ framework-66d32731bdd20e83.js:9
ox @ framework-66d32731bdd20e83.js:9
x @ framework-66d32731bdd20e83.js:33
T @ framework-66d32731bdd20e83.js:33
_app-d844a6410e282f58.js:141 
        
        
GET https://faustjs.org/api/faust/auth/token 401 (Unauthorized)
o9 @ _app-d844a6410e282f58.js:141
ae @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
uU @ framework-66d32731bdd20e83.js:9
oV @ framework-66d32731bdd20e83.js:9
oP @ framework-66d32731bdd20e83.js:9
r8 @ framework-66d32731bdd20e83.js:9
(anonymous) @ framework-66d32731bdd20e83.js:9
oU @ framework-66d32731bdd20e83.js:9
ox @ framework-66d32731bdd20e83.js:9
x @ framework-66d32731bdd20e83.js:33
T @ framework-66d32731bdd20e83.js:33
_app-d844a6410e282f58.js:141 


Uncaught (in promise) ApolloError: Unterminated string in JSON at position 360448 (line 1 column 360449)
    at new N (_app-d844a6410e282f58.js:141:10319)
    at _app-d844a6410e282f58.js:141:146860
    at I (_app-d844a6410e282f58.js:141:111042)
    at _app-d844a6410e282f58.js:141:110968
    at new Promise (<anonymous>)
    at Object.then (_app-d844a6410e282f58.js:141:110935)
    at Object.error (_app-d844a6410e282f58.js:141:111052)
    at eC (_app-d844a6410e282f58.js:141:29434)
    at ex (_app-d844a6410e282f58.js:141:29797)
    at N.error (_app-d844a6410e282f58.js:141:30358)
N @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
I @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
then @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
eC @ _app-d844a6410e282f58.js:141
ex @ _app-d844a6410e282f58.js:141
N.error @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
iM @ _app-d844a6410e282f58.js:141
error @ _app-d844a6410e282f58.js:141
eC @ _app-d844a6410e282f58.js:141
ex @ _app-d844a6410e282f58.js:141
N.error @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
$ @ _app-d844a6410e282f58.js:141
error @ _app-d844a6410e282f58.js:141
eC @ _app-d844a6410e282f58.js:141
ex @ _app-d844a6410e282f58.js:141
N.error @ _app-d844a6410e282f58.js:141
tG @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
await in (anonymous) (async)
(anonymous) @ _app-d844a6410e282f58.js:133
uU @ framework-66d32731bdd20e83.js:9
oV @ framework-66d32731bdd20e83.js:9
o @ framework-66d32731bdd20e83.js:9
x @ framework-66d32731bdd20e83.js:33
T @ framework-66d32731bdd20e83.js:33
_app-d844a6410e282f58.js:141 


Uncaught (in promise) ApolloError: Unterminated string in JSON at position 65536 (line 1 column 65537)
    at new N (_app-d844a6410e282f58.js:141:10319)
    at _app-d844a6410e282f58.js:141:146860
    at I (_app-d844a6410e282f58.js:141:111042)
    at _app-d844a6410e282f58.js:141:110968
    at new Promise (<anonymous>)
    at Object.then (_app-d844a6410e282f58.js:141:110935)
    at Object.error (_app-d844a6410e282f58.js:141:111052)
    at eC (_app-d844a6410e282f58.js:141:29434)
    at ex (_app-d844a6410e282f58.js:141:29797)
    at N.error (_app-d844a6410e282f58.js:141:30358)
N @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
I @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
then @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
eC @ _app-d844a6410e282f58.js:141
ex @ _app-d844a6410e282f58.js:141
N.error @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
iM @ _app-d844a6410e282f58.js:141
error @ _app-d844a6410e282f58.js:141
eC @ _app-d844a6410e282f58.js:141
ex @ _app-d844a6410e282f58.js:141
N.error @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
$ @ _app-d844a6410e282f58.js:141
error @ _app-d844a6410e282f58.js:141
eC @ _app-d844a6410e282f58.js:141
ex @ _app-d844a6410e282f58.js:141
N.error @ _app-d844a6410e282f58.js:141
tG @ _app-d844a6410e282f58.js:141
(anonymous) @ _app-d844a6410e282f58.js:141
await in (anonymous) (async)
(anonymous) @ _app-d844a6410e282f58.js:133
uU @ framework-66d32731bdd20e83.js:9
oV @ framework-66d32731bdd20e83.js:9
o @ framework-66d32731bdd20e83.js:9
x @ framework-66d32731bdd20e83.js:33
T @ framework-66d32731bdd20e83.js:33
```

### Steps to reproduce

On Google Chrome or Developer Google Chrome (Mac Ventura 13.6.1), select the Search field. Type in the box. 

### @faustwp/core Version

N/A

### @faustwp/cli Version

N/A

### FaustWP Plugin Version

N/A

### WordPress Version

N/A

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

**Comment by theodesp** [comment]
Hey @miacias it should be working now. Thank you for the heads up!
