### ISSUE TITLE
useLogin : Error - Invalid response for authorize handler: SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by cedricrabarijohn** [wpengine/faustjs#1997]
### Description

Hi. I'm trying to create a simple authentication flow using the local based authentication described inside the docs [https://faustjs.org/guide/how-to-handle-authentication](https://faustjs.org/guide/how-to-handle-authentication) . I'm using the following packages
```
"@faustwp/cli": "^3.0.2",
"@faustwp/core": "^3.0.1",
```

My problem is that after a login , the authorization code generation api works well, but then the client api call to
http://localhost:3000/api/faust/auth/token/?code=5yQxzt28OTJzmLlNzMyrPX9742WWSmMHEZrjfWBI%2FMjlADd%2Fzb0eMQUuOT1YGHecpCOoWrVIrkauKQumo0WHFw%3D%3D returns a simple 500 internal server error. The error code show in the response is a single json containing

```
{
    "error": "Internal Server Error"
}
```

### Steps to reproduce

1. Clone or just use a working faust project ( using pages router )
2. Create a new page (ex : login.jsx)
3. Paste the following code snippet inside the new page created above

```jsx
import { useLogin } from '@faustwp/core';
import { useState } from 'react';

export default function Login() {
  const [usernameEmail, setUsernameEmail] = useState('');
  const [password, setPassword] = useState('');
  const { login, loading, data, error } = useLogin();

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();

        login(usernameEmail, password);
      }}>
      <fieldset>
        <label htmlFor="usernameEmail">Username or Email</label>
        <input
          id="usernameEmail"
          type="text"
          disabled={loading === true}
          value={usernameEmail}
          onChange={(e) => setUsernameEmail(e.target.value)}
        />
      </fieldset>

      <fieldset>
        <label htmlFor="password">Password</label>
        <input
          id="password"
          type="password"
          disabled={loading === true}
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
      </fieldset>

      {data?.generateAuthorizationCode.error && (
        <p
          dangerouslySetInnerHTML={{
            __html: data.generateAuthorizationCode.error,
          }}
        />
      )}

      <fieldset>
        <button type="submit">Login</button>
      </fieldset>
    </form>
  );
}
```
4. Start the project
```
npm run dev
```

5. Navigate to http://localhost:3000/login
6. Enter valid login credentials

# 

## The authorization code generation (Working well)

![Screenshot from 2024-12-02 17-39-13](https://github.com/user-attachments/assets/6a55b130-d376-4b96-84b1-34ebfb90600b)

## The token generation (Not working)
![image](https://github.com/user-attachments/assets/7d6db021-1bcf-414b-b22e-b6f12a81a731)

## My Nextjs error in my console
```
error - Invalid response for authorize handler: SyntaxError: Unexpected non-whitespace character after JSON at position 4
at JSON.parse (<anonymous>)
at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)
at successSteps (node:internal/deps/undici/undici:5470:27)
at fullyReadBody (node:internal/deps/undici/undici:4381:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async consumeBody (node:internal/deps/undici/undici:5479:7)
at async OAuth.fetch (/app/node_modules/@faustwp/core/dist/cjs/server/auth/token.js:77:24)
at async authorizeHandler (/app/node_modules/@faustwp/core/dist/cjs/server/auth/middleware.js:30:24)
at async /app/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:83:28
at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
at async DevServer.runApi (/app/node_modules/next/dist/server/next-server.js:598:9)
at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
at async DevServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:817:17)
at async /app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
  GET /api/faust/auth/token/?code=%2BuUUyAja1aXBD4gv0k9%2Bvju7XjTHYY8rfJQ0Sfjz5nptFtque4z54GFoUX3Q8eKdziQcdGArM6HcGjdrl6tIRw%3D%3D 500 in 1185ms
```

### @faustwp/core Version

3.0.1

### @faustwp/cli Version

3.0.2

### FaustWP Plugin Version

1.4.1

### WordPress Version

6.7.1

## My dependencies in my package.json file

```json
"dependencies": {
    "@apollo/client": "^3.10.5",
    "@commitlint/cli": "^19.5.0",
    "@commitlint/config-conventional": "^19.5.0",
    "@emotion/cache": "^11.13.5",
    "@emotion/react": "^11.13.5",
    "@emotion/server": "^11.11.0",
    "@emotion/styled": "^11.13.5",
    "@faustwp/cli": "^3.0.2",
    "@faustwp/core": "^3.0.1",
    "@fontsource/material-icons": "^5.1.0",
    "@fontsource/roboto": "^5.1.0",
    "@graphql-codegen/typescript": "^4.1.1",
    "@graphql-codegen/typescript-operations": "^4.3.1",
    "@mui/icons-material": "^6.1.8",
    "@mui/material": "^6.1.8",
    "@mui/material-nextjs": "^6.1.8",
    "@popperjs/core": "^2.11.8",
    "@rollbar/react": "^0.12.0-beta",
    "@sentry/nextjs": "^8.41.0",
    "@storybook/addon-themes": "^8.4.6",
    "@types/react-intl": "^3.0.0",
    "@uidotdev/usehooks": "^2.4.1",
    "axios": "^1.7.7",
    "commitlint": "^19.5.0",
    "dotenv": "^16.4.5",
    "flag-icons": "^7.2.3",
    "graphql": "^16.8.2",
    "husky": "^9.1.6",
    "isomorphic-unfetch": "^4.0.2",
    "next": "^14.2.12",
    "next-secure-headers": "^2.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-infinite-logo-slider": "^1.1.4",
    "react-intl": "^6.8.7",
    "rollbar": "^2.26.4",
    "sass": "^1.80.6",
    "swiper": "^11.1.15"
  },
  "devDependencies": {
    "@chromatic-com/storybook": "^3.2.2",
    "@graphql-codegen/cli": "^5.0.2",
    "@graphql-codegen/client-preset": "^4.3.0",
    "@parcel/watcher": "^2.4.1",
    "@storybook/addon-essentials": "^8.4.6",
    "@storybook/addon-interactions": "^8.4.6",
    "@storybook/addon-onboarding": "^8.4.6",
    "@storybook/blocks": "^8.4.6",
    "@storybook/nextjs": "^8.4.6",
    "@storybook/react": "^8.4.6",
    "@storybook/test": "^8.4.6",
    "@types/node": "^18.16.1",
    "@types/react": "^18.3.3",
    "@typescript-eslint/eslint-plugin": "^8.15.0",
    "@typescript-eslint/parser": "^8.15.0",
    "concurrently": "^8.2.2",
    "eslint": "^9.15.0",
    "eslint-config-next": "^15.0.3",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-jsx-a11y": "^6.10.2",
    "eslint-plugin-next": "^0.0.0",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-storybook": "^0.11.1",
    "prettier": "^3.3.3",
    "storybook": "^8.4.6",
    "typescript": "^5.4.5"
  },
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

**Comment by cedricrabarijohn** [comment]
@theodesp sorry for mentionning. For additionnal informations, I have a basic auth on my CMS , could it be the reason ?

**Comment by cedricrabarijohn** [comment]
After days of investigations, I've concluded it was because of the basic auth active on certain urls 

    ${wpUrl}/?rest_route=/faustwp/v1/authorize

and

    ${wpUrl}/?rest_route=/wpac/v1/authorize

Once I deactivated the basic auth on those urls via my traefik configuration, I was able to properly have my authentication working.

I will close this ticket for now since the problem has been solved.

**Comment by theodesp** [comment]
@cedricrabarijohn Thank you for your effort. I think we have an item in the backlog to mention triggering a message in case basic auth is used.

**Comment by cedricrabarijohn** [comment]
I think allowing developers to put basic auth credentials inside environment variables would be useful, then modify fetch calls to insert them dynamically in their respective headers.

An example of fetch calls that have hard-coded headers in their options : ( packages/faustwp-core/src/server/auth/token.ts )

![image](https://github.com/user-attachments/assets/f02f536b-3038-44cc-b78e-f4a677369994)
