### ISSUE TITLE
Bug: SyntaxError: Unexpected token '.' on Node v14

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#498]
When running the Faust.js `next/getting-started` example from Node v12, the following error occurs when navigating to a page:

```
SyntaxError: Unexpected token '.'
    at Object../node_modules/@faustjs/next/dist/mjs/client.js (/Users/blakewilson/Desktop/my-app/.next/server/pages/_app.js:295:1)
    at __webpack_require__ (/Users/blakewilson/Desktop/my-app/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/@faustjs/next/dist/mjs/index.js:2:65)
    at Object../node_modules/@faustjs/next/dist/mjs/index.js (/Users/blakewilson/Desktop/my-app/.next/server/pages/_app.js:482:1)
    at __webpack_require__ (/Users/blakewilson/Desktop/my-app/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:6:71)
    at Object../src/pages/_app.tsx (/Users/blakewilson/Desktop/my-app/.next/server/pages/_app.js:55:1)
    at __webpack_require__ (/Users/blakewilson/Desktop/my-app/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/blakewilson/Desktop/my-app/.next/server/pages/_app.js:525:39)
    at /Users/blakewilson/Desktop/my-app/.next/server/pages/_app.js:526:28
```

## Applicable Versions

- `@faustjs/core` version: 0.10.2
- `@faustjs/react` version: 0.10.2
- `@faustjs/next` version: 0.10.2
- WordPress version: N/A
- Node Version: 12.17.0

## Steps To Reproduce

1. Use Node v12
2. [Follow the Faust.js getting started instructions](https://faustjs.org/docs/next/getting-started)
3. `npm run dev`

**Comment by andresclua** [comment]
using Node v12.16.1 and have same error.
